name: Backend CI - Prodsy API

on:
  push:
    branches:
      - main      
      - develop  
  pull_request:
    branches:
      - main      
      - develop  

jobs:
  build_and_test: 
    name: Construir e Testar Aplicação Backend 
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      
      - name: 1. Baixar o código (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js versão ${{ matrix.node-version }}
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node-version }} 

      - name: 3. Instalar Dependências
        run: npm ci

      - name: 5. Rodar Testes (Unitários/Integração)
        run: npm test 
